<?php

namespace Database\Seeders;

use App\Models\Kota;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [
            ["id" => "1", "nama_kota" => "Kabupaten Aceh Barat", "provinsi_id" => "21"],
            ["id" => "2", "nama_kota" => "Kabupaten Aceh Barat Daya", "provinsi_id" => "21"],
            ["id" => "3", "nama_kota" => "Kabupaten Aceh Besar", "provinsi_id" => "21"],
            ["id" => "4", "nama_kota" => "Kabupaten Aceh Jaya", "provinsi_id" => "21"],
            ["id" => "5", "nama_kota" => "Kabupaten Aceh Selatan", "provinsi_id" => "21"],
            ["id" => "6", "nama_kota" => "Kabupaten Aceh Singkil", "provinsi_id" => "21"],
            ["id" => "7", "nama_kota" => "Kabupaten Aceh Tamiang", "provinsi_id" => "21"],
            ["id" => "8", "nama_kota" => "Kabupaten Aceh Tengah", "provinsi_id" => "21"],
            ["id" => "9", "nama_kota" => "Kabupaten Aceh Tenggara", "provinsi_id" => "21"],
            ["id" => "10", "nama_kota" => "Kabupaten Aceh Timur", "provinsi_id" => "21"],
            ["id" => "11", "nama_kota" => "Kabupaten Aceh Utara", "provinsi_id" => "21"],
            ["id" => "12", "nama_kota" => "Kabupaten Agam", "provinsi_id" => "32"],
            ["id" => "13", "nama_kota" => "Kabupaten Alor", "provinsi_id" => "23"],
            ["id" => "14", "nama_kota" => "Kota Ambon", "provinsi_id" => "19"],
            ["id" => "15", "nama_kota" => "Kabupaten Asahan", "provinsi_id" => "34"],
            ["id" => "16", "nama_kota" => "Kabupaten Asmat", "provinsi_id" => "24"],
            ["id" => "17", "nama_kota" => "Kabupaten Badung", "provinsi_id" => "1"],
            ["id" => "18", "nama_kota" => "Kabupaten Balangan", "provinsi_id" => "13"],
            ["id" => "19", "nama_kota" => "Kota Balikpapan", "provinsi_id" => "15"],
            ["id" => "20", "nama_kota" => "Kota Banda Aceh", "provinsi_id" => "21"],
            ["id" => "21", "nama_kota" => "Kota Bandar Lampung", "provinsi_id" => "18"],
            ["id" => "22", "nama_kota" => "Kabupaten Bandung", "provinsi_id" => "9"],
            ["id" => "23", "nama_kota" => "Kota Bandung", "provinsi_id" => "9"],
            ["id" => "24", "nama_kota" => "Kabupaten Bandung Barat", "provinsi_id" => "9"],
            ["id" => "25", "nama_kota" => "Kabupaten Banggai", "provinsi_id" => "29"],
            ["id" => "26", "nama_kota" => "Kabupaten Banggai Kepulauan", "provinsi_id" => "29"],
            ["id" => "27", "nama_kota" => "Kabupaten Bangka", "provinsi_id" => "2"],
            ["id" => "28", "nama_kota" => "Kabupaten Bangka Barat", "provinsi_id" => "2"],
            ["id" => "29", "nama_kota" => "Kabupaten Bangka Selatan", "provinsi_id" => "2"],
            ["id" => "30", "nama_kota" => "Kabupaten Bangka Tengah", "provinsi_id" => "2"],
            ["id" => "31", "nama_kota" => "Kabupaten Bangkalan", "provinsi_id" => "11"],
            ["id" => "32", "nama_kota" => "Kabupaten Bangli", "provinsi_id" => "1"],
            ["id" => "33", "nama_kota" => "Kabupaten Banjar", "provinsi_id" => "13"],
            ["id" => "34", "nama_kota" => "Kota Banjar", "provinsi_id" => "9"],
            ["id" => "35", "nama_kota" => "Kota Banjarbaru", "provinsi_id" => "13"],
            ["id" => "36", "nama_kota" => "Kota Banjarmasin", "provinsi_id" => "13"],
            ["id" => "37", "nama_kota" => "Kabupaten Banjarnegara", "provinsi_id" => "10"],
            ["id" => "38", "nama_kota" => "Kabupaten Bantaeng", "provinsi_id" => "28"],
            ["id" => "39", "nama_kota" => "Kabupaten Bantul", "provinsi_id" => "5"],
            ["id" => "40", "nama_kota" => "Kabupaten Banyuasin", "provinsi_id" => "33"],
            ["id" => "41", "nama_kota" => "Kabupaten Banyumas", "provinsi_id" => "10"],
            ["id" => "42", "nama_kota" => "Kabupaten Banyuwangi", "provinsi_id" => "11"],
            ["id" => "43", "nama_kota" => "Kabupaten Barito Kuala", "provinsi_id" => "13"],
            ["id" => "44", "nama_kota" => "Kabupaten Barito Selatan", "provinsi_id" => "14"],
            ["id" => "45", "nama_kota" => "Kabupaten Barito Timur", "provinsi_id" => "14"],
            ["id" => "46", "nama_kota" => "Kabupaten Barito Utara", "provinsi_id" => "14"],
            ["id" => "47", "nama_kota" => "Kabupaten Barru", "provinsi_id" => "28"],
            ["id" => "48", "nama_kota" => "Kota Batam", "provinsi_id" => "17"],
            ["id" => "49", "nama_kota" => "Kabupaten Batang", "provinsi_id" => "10"],
            ["id" => "50", "nama_kota" => "Kabupaten Batang Hari", "provinsi_id" => "8"],
            ["id" => "51", "nama_kota" => "Kota Batu", "provinsi_id" => "11"],
            ["id" => "52", "nama_kota" => "Kabupaten Batu Bara", "provinsi_id" => "34"],
            ["id" => "53", "nama_kota" => "Kota Bau-Bau", "provinsi_id" => "30"],
            ["id" => "54", "nama_kota" => "Kabupaten Bekasi", "provinsi_id" => "9"],
            ["id" => "55", "nama_kota" => "Kota Bekasi", "provinsi_id" => "9"],
            ["id" => "56", "nama_kota" => "Kabupaten Belitung", "provinsi_id" => "2"],
            ["id" => "57", "nama_kota" => "Kabupaten Belitung Timur", "provinsi_id" => "2"],
            ["id" => "58", "nama_kota" => "Kabupaten Belu", "provinsi_id" => "23"],
            ["id" => "59", "nama_kota" => "Kabupaten Bener Meriah", "provinsi_id" => "21"],
            ["id" => "60", "nama_kota" => "Kabupaten Bengkalis", "provinsi_id" => "26"],
            ["id" => "61", "nama_kota" => "Kabupaten Bengkayang", "provinsi_id" => "12"],
            ["id" => "62", "nama_kota" => "Kota Bengkulu", "provinsi_id" => "4"],
            ["id" => "63", "nama_kota" => "Kabupaten Bengkulu Selatan", "provinsi_id" => "4"],
            ["id" => "64", "nama_kota" => "Kabupaten Bengkulu Tengah", "provinsi_id" => "4"],
            ["id" => "65", "nama_kota" => "Kabupaten Bengkulu Utara", "provinsi_id" => "4"],
            ["id" => "66", "nama_kota" => "Kabupaten Berau", "provinsi_id" => "15"],
            ["id" => "67", "nama_kota" => "Kabupaten Biak Numfor", "provinsi_id" => "24"],
            ["id" => "68", "nama_kota" => "Kabupaten Bima", "provinsi_id" => "22"],
            ["id" => "69", "nama_kota" => "Kota Bima", "provinsi_id" => "22"],
            ["id" => "70", "nama_kota" => "Kota Binjai", "provinsi_id" => "34"],
            ["id" => "71", "nama_kota" => "Kabupaten Bintan", "provinsi_id" => "17"],
            ["id" => "72", "nama_kota" => "Kabupaten Bireuen", "provinsi_id" => "21"],
            ["id" => "73", "nama_kota" => "Kota Bitung", "provinsi_id" => "31"],
            ["id" => "74", "nama_kota" => "Kabupaten Blitar", "provinsi_id" => "11"],
            ["id" => "75", "nama_kota" => "Kota Blitar", "provinsi_id" => "11"],
            ["id" => "76", "nama_kota" => "Kabupaten Blora", "provinsi_id" => "10"],
            ["id" => "77", "nama_kota" => "Kabupaten Boalemo", "provinsi_id" => "7"],
            ["id" => "78", "nama_kota" => "Kabupaten Bogor", "provinsi_id" => "9"],
            ["id" => "79", "nama_kota" => "Kota Bogor", "provinsi_id" => "9"],
            ["id" => "80", "nama_kota" => "Kabupaten Bojonegoro", "provinsi_id" => "11"],
            ["id" => "81", "nama_kota" => "Kabupaten Bolaang Mongondow (Bolmong)", "provinsi_id" => "31"],
            ["id" => "82", "nama_kota" => "Kabupaten Bolaang Mongondow Selatan", "provinsi_id" => "31"],
            ["id" => "83", "nama_kota" => "Kabupaten Bolaang Mongondow Timur", "provinsi_id" => "31"],
            ["id" => "84", "nama_kota" => "Kabupaten Bolaang Mongondow Utara", "provinsi_id" => "31"],
            ["id" => "85", "nama_kota" => "Kabupaten Bombana", "provinsi_id" => "30"],
            ["id" => "86", "nama_kota" => "Kabupaten Bondowoso", "provinsi_id" => "11"],
            ["id" => "87", "nama_kota" => "Kabupaten Bone", "provinsi_id" => "28"],
            ["id" => "88", "nama_kota" => "Kabupaten Bone Bolango", "provinsi_id" => "7"],
            ["id" => "89", "nama_kota" => "Kota Bontang", "provinsi_id" => "15"],
            ["id" => "90", "nama_kota" => "Kabupaten Boven Digoel", "provinsi_id" => "24"],
            ["id" => "91", "nama_kota" => "Kabupaten Boyolali", "provinsi_id" => "10"],
            ["id" => "92", "nama_kota" => "Kabupaten Brebes", "provinsi_id" => "10"],
            ["id" => "93", "nama_kota" => "Kota Bukittinggi", "provinsi_id" => "32"],
            ["id" => "94", "nama_kota" => "Kabupaten Buleleng", "provinsi_id" => "1"],
            ["id" => "95", "nama_kota" => "Kabupaten Bulukumba", "provinsi_id" => "28"],
            ["id" => "96", "nama_kota" => "Kabupaten Bulungan (Bulongan)", "provinsi_id" => "16"],
            ["id" => "97", "nama_kota" => "Kabupaten Bungo", "provinsi_id" => "8"],
            ["id" => "98", "nama_kota" => "Kabupaten Buol", "provinsi_id" => "29"],
            ["id" => "99", "nama_kota" => "Kabupaten Buru", "provinsi_id" => "19"],
            ["id" => "100", "nama_kota" => "Kabupaten Buru Selatan", "provinsi_id" => "19"],
            ["id" => "101", "nama_kota" => "Kabupaten Buton", "provinsi_id" => "30"],
            ["id" => "102", "nama_kota" => "Kabupaten Buton Utara", "provinsi_id" => "30"],
            ["id" => "103", "nama_kota" => "Kabupaten Ciamis", "provinsi_id" => "9"],
            ["id" => "104", "nama_kota" => "Kabupaten Cianjur", "provinsi_id" => "9"],
            ["id" => "105", "nama_kota" => "Kabupaten Cilacap", "provinsi_id" => "10"],
            ["id" => "106", "nama_kota" => "Kota Cilegon", "provinsi_id" => "3"],
            ["id" => "107", "nama_kota" => "Kota Cimahi", "provinsi_id" => "9"],
            ["id" => "108", "nama_kota" => "Kabupaten Cirebon", "provinsi_id" => "9"],
            ["id" => "109", "nama_kota" => "Kota Cirebon", "provinsi_id" => "9"],
            ["id" => "110", "nama_kota" => "Kabupaten Dairi", "provinsi_id" => "34"],
            ["id" => "111", "nama_kota" => "Kabupaten Deiyai (Deliyai)", "provinsi_id" => "24"],
            ["id" => "112", "nama_kota" => "Kabupaten Deli Serdang", "provinsi_id" => "34"],
            ["id" => "113", "nama_kota" => "Kabupaten Demak", "provinsi_id" => "10"],
            ["id" => "114", "nama_kota" => "Kota Denpasar", "provinsi_id" => "1"],
            ["id" => "115", "nama_kota" => "Kota Depok", "provinsi_id" => "9"],
            ["id" => "116", "nama_kota" => "Kabupaten Dharmasraya", "provinsi_id" => "32"],
            ["id" => "117", "nama_kota" => "Kabupaten Dogiyai", "provinsi_id" => "24"],
            ["id" => "118", "nama_kota" => "Kabupaten Dompu", "provinsi_id" => "22"],
            ["id" => "119", "nama_kota" => "Kabupaten Donggala", "provinsi_id" => "29"],
            ["id" => "120", "nama_kota" => "Kota Dumai", "provinsi_id" => "26"],
            ["id" => "121", "nama_kota" => "Kabupaten Empat Lawang", "provinsi_id" => "33"],
            ["id" => "122", "nama_kota" => "Kabupaten Ende", "provinsi_id" => "23"],
            ["id" => "123", "nama_kota" => "Kabupaten Enrekang", "provinsi_id" => "28"],
            ["id" => "124", "nama_kota" => "Kabupaten Fakfak", "provinsi_id" => "25"],
            ["id" => "125", "nama_kota" => "Kabupaten Flores Timur", "provinsi_id" => "23"],
            ["id" => "126", "nama_kota" => "Kabupaten Garut", "provinsi_id" => "9"],
            ["id" => "127", "nama_kota" => "Kabupaten Gayo Lues", "provinsi_id" => "21"],
            ["id" => "128", "nama_kota" => "Kabupaten Gianyar", "provinsi_id" => "1"],
            ["id" => "129", "nama_kota" => "Kabupaten Gorontalo", "provinsi_id" => "7"],
            ["id" => "130", "nama_kota" => "Kota Gorontalo", "provinsi_id" => "7"],
            ["id" => "131", "nama_kota" => "Kabupaten Gorontalo Utara", "provinsi_id" => "7"],
            ["id" => "132", "nama_kota" => "Kabupaten Gowa", "provinsi_id" => "28"],
            ["id" => "133", "nama_kota" => "Kabupaten Gresik", "provinsi_id" => "11"],
            ["id" => "134", "nama_kota" => "Kabupaten Grobogan", "provinsi_id" => "10"],
            ["id" => "135", "nama_kota" => "Kabupaten Gunung Kidul", "provinsi_id" => "5"],
            ["id" => "136", "nama_kota" => "Kabupaten Gunung Mas", "provinsi_id" => "14"],
            ["id" => "137", "nama_kota" => "Kota Gunungsitoli", "provinsi_id" => "34"],
            ["id" => "138", "nama_kota" => "Kabupaten Halmahera Barat", "provinsi_id" => "20"],
            ["id" => "139", "nama_kota" => "Kabupaten Halmahera Selatan", "provinsi_id" => "20"],
            ["id" => "140", "nama_kota" => "Kabupaten Halmahera Tengah", "provinsi_id" => "20"],
            ["id" => "141", "nama_kota" => "Kabupaten Halmahera Timur", "provinsi_id" => "20"],
            ["id" => "142", "nama_kota" => "Kabupaten Halmahera Utara", "provinsi_id" => "20"],
            ["id" => "143", "nama_kota" => "Kabupaten Hulu Sungai Selatan", "provinsi_id" => "13"],
            ["id" => "144", "nama_kota" => "Kabupaten Hulu Sungai Tengah", "provinsi_id" => "13"],
            ["id" => "145", "nama_kota" => "Kabupaten Hulu Sungai Utara", "provinsi_id" => "13"],
            ["id" => "146", "nama_kota" => "Kabupaten Humbang Hasundutan", "provinsi_id" => "34"],
            ["id" => "147", "nama_kota" => "Kabupaten Indragiri Hilir", "provinsi_id" => "26"],
            ["id" => "148", "nama_kota" => "Kabupaten Indragiri Hulu", "provinsi_id" => "26"],
            ["id" => "149", "nama_kota" => "Kabupaten Indramayu", "provinsi_id" => "9"],
            ["id" => "150", "nama_kota" => "Kabupaten Intan Jaya", "provinsi_id" => "24"],
            ["id" => "151", "nama_kota" => "Kota Jakarta Barat", "provinsi_id" => "6"],
            ["id" => "152", "nama_kota" => "Kota Jakarta Pusat", "provinsi_id" => "6"],
            ["id" => "153", "nama_kota" => "Kota Jakarta Selatan", "provinsi_id" => "6"],
            ["id" => "154", "nama_kota" => "Kota Jakarta Timur", "provinsi_id" => "6"],
            ["id" => "155", "nama_kota" => "Kota Jakarta Utara", "provinsi_id" => "6"],
            ["id" => "156", "nama_kota" => "Kota Jambi", "provinsi_id" => "8"],
            ["id" => "157", "nama_kota" => "Kabupaten Jayapura", "provinsi_id" => "24"],
            ["id" => "158", "nama_kota" => "Kota Jayapura", "provinsi_id" => "24"],
            ["id" => "159", "nama_kota" => "Kabupaten Jayawijaya", "provinsi_id" => "24"],
            ["id" => "160", "nama_kota" => "Kabupaten Jember", "provinsi_id" => "11"],
            ["id" => "161", "nama_kota" => "Kabupaten Jembrana", "provinsi_id" => "1"],
            ["id" => "162", "nama_kota" => "Kabupaten Jeneponto", "provinsi_id" => "28"],
            ["id" => "163", "nama_kota" => "Kabupaten Jepara", "provinsi_id" => "10"],
            ["id" => "164", "nama_kota" => "Kabupaten Jombang", "provinsi_id" => "11"],
            ["id" => "165", "nama_kota" => "Kabupaten Kaimana", "provinsi_id" => "25"],
            ["id" => "166", "nama_kota" => "Kabupaten Kampar", "provinsi_id" => "26"],
            ["id" => "167", "nama_kota" => "Kabupaten Kapuas", "provinsi_id" => "14"],
            ["id" => "168", "nama_kota" => "Kabupaten Kapuas Hulu", "provinsi_id" => "12"],
            ["id" => "169", "nama_kota" => "Kabupaten Karanganyar", "provinsi_id" => "10"],
            ["id" => "170", "nama_kota" => "Kabupaten Karangasem", "provinsi_id" => "1"],
            ["id" => "171", "nama_kota" => "Kabupaten Karawang", "provinsi_id" => "9"],
            ["id" => "172", "nama_kota" => "Kabupaten Karimun", "provinsi_id" => "17"],
            ["id" => "173", "nama_kota" => "Kabupaten Karo", "provinsi_id" => "34"],
            ["id" => "174", "nama_kota" => "Kabupaten Katingan", "provinsi_id" => "14"],
            ["id" => "175", "nama_kota" => "Kabupaten Kaur", "provinsi_id" => "4"],
            ["id" => "176", "nama_kota" => "Kabupaten Kayong Utara", "provinsi_id" => "12"],
            ["id" => "177", "nama_kota" => "Kabupaten Kebumen", "provinsi_id" => "10"],
            ["id" => "178", "nama_kota" => "Kabupaten Kediri", "provinsi_id" => "11"],
            ["id" => "179", "nama_kota" => "Kota Kediri", "provinsi_id" => "11"],
            ["id" => "180", "nama_kota" => "Kabupaten Keerom", "provinsi_id" => "24"],
            ["id" => "181", "nama_kota" => "Kabupaten Kendal", "provinsi_id" => "10"],
            ["id" => "182", "nama_kota" => "Kota Kendari", "provinsi_id" => "30"],
            ["id" => "183", "nama_kota" => "Kabupaten Kepahiang", "provinsi_id" => "4"],
            ["id" => "184", "nama_kota" => "Kabupaten Kepulauan Anambas", "provinsi_id" => "17"],
            ["id" => "185", "nama_kota" => "Kabupaten Kepulauan Aru", "provinsi_id" => "19"],
            ["id" => "186", "nama_kota" => "Kabupaten Kepulauan Mentawai", "provinsi_id" => "32"],
            ["id" => "187", "nama_kota" => "Kabupaten Kepulauan Meranti", "provinsi_id" => "26"],
            ["id" => "188", "nama_kota" => "Kabupaten Kepulauan Sangihe", "provinsi_id" => "31"],
            ["id" => "189", "nama_kota" => "Kabupaten Kepulauan Seribu", "provinsi_id" => "6"],
            ["id" => "190", "nama_kota" => "Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)", "provinsi_id" => "31"],
            ["id" => "191", "nama_kota" => "Kabupaten Kepulauan Sula", "provinsi_id" => "20"],
            ["id" => "192", "nama_kota" => "Kabupaten Kepulauan Talaud", "provinsi_id" => "31"],
            ["id" => "193", "nama_kota" => "Kabupaten Kepulauan Yapen (Yapen Waropen)", "provinsi_id" => "24"],
            ["id" => "194", "nama_kota" => "Kabupaten Kerinci", "provinsi_id" => "8"],
            ["id" => "195", "nama_kota" => "Kabupaten Ketapang", "provinsi_id" => "12"],
            ["id" => "196", "nama_kota" => "Kabupaten Klaten", "provinsi_id" => "10"],
            ["id" => "197", "nama_kota" => "Kabupaten Klungkung", "provinsi_id" => "1"],
            ["id" => "198", "nama_kota" => "Kabupaten Kolaka", "provinsi_id" => "30"],
            ["id" => "199", "nama_kota" => "Kabupaten Kolaka Utara", "provinsi_id" => "30"],
            ["id" => "200", "nama_kota" => "Kabupaten Konawe", "provinsi_id" => "30"],
            ["id" => "201", "nama_kota" => "Kabupaten Konawe Selatan", "provinsi_id" => "30"],
            ["id" => "202", "nama_kota" => "Kabupaten Konawe Utara", "provinsi_id" => "30"],
            ["id" => "203", "nama_kota" => "Kabupaten Kotabaru", "provinsi_id" => "13"],
            ["id" => "204", "nama_kota" => "Kota Kotamobagu", "provinsi_id" => "31"],
            ["id" => "205", "nama_kota" => "Kabupaten Kotawaringin Barat", "provinsi_id" => "14"],
            ["id" => "206", "nama_kota" => "Kabupaten Kotawaringin Timur", "provinsi_id" => "14"],
            ["id" => "207", "nama_kota" => "Kabupaten Kuantan Singingi", "provinsi_id" => "26"],
            ["id" => "208", "nama_kota" => "Kabupaten Kubu Raya", "provinsi_id" => "12"],
            ["id" => "209", "nama_kota" => "Kabupaten Kudus", "provinsi_id" => "10"],
            ["id" => "210", "nama_kota" => "Kabupaten Kulon Progo", "provinsi_id" => "5"],
            ["id" => "211", "nama_kota" => "Kabupaten Kuningan", "provinsi_id" => "9"],
            ["id" => "212", "nama_kota" => "Kabupaten Kupang", "provinsi_id" => "23"],
            ["id" => "213", "nama_kota" => "Kota Kupang", "provinsi_id" => "23"],
            ["id" => "214", "nama_kota" => "Kabupaten Kutai Barat", "provinsi_id" => "15"],
            ["id" => "215", "nama_kota" => "Kabupaten Kutai Kartanegara", "provinsi_id" => "15"],
            ["id" => "216", "nama_kota" => "Kabupaten Kutai Timur", "provinsi_id" => "15"],
            ["id" => "217", "nama_kota" => "Kabupaten Labuhan Batu", "provinsi_id" => "34"],
            ["id" => "218", "nama_kota" => "Kabupaten Labuhan Batu Selatan", "provinsi_id" => "34"],
            ["id" => "219", "nama_kota" => "Kabupaten Labuhan Batu Utara", "provinsi_id" => "34"],
            ["id" => "220", "nama_kota" => "Kabupaten Lahat", "provinsi_id" => "33"],
            ["id" => "221", "nama_kota" => "Kabupaten Lamandau", "provinsi_id" => "14"],
            ["id" => "222", "nama_kota" => "Kabupaten Lamongan", "provinsi_id" => "11"],
            ["id" => "223", "nama_kota" => "Kabupaten Lampung Barat", "provinsi_id" => "18"],
            ["id" => "224", "nama_kota" => "Kabupaten Lampung Selatan", "provinsi_id" => "18"],
            ["id" => "225", "nama_kota" => "Kabupaten Lampung Tengah", "provinsi_id" => "18"],
            ["id" => "226", "nama_kota" => "Kabupaten Lampung Timur", "provinsi_id" => "18"],
            ["id" => "227", "nama_kota" => "Kabupaten Lampung Utara", "provinsi_id" => "18"],
            ["id" => "228", "nama_kota" => "Kabupaten Landak", "provinsi_id" => "12"],
            ["id" => "229", "nama_kota" => "Kabupaten Langkat", "provinsi_id" => "34"],
            ["id" => "230", "nama_kota" => "Kota Langsa", "provinsi_id" => "21"],
            ["id" => "231", "nama_kota" => "Kabupaten Lanny Jaya", "provinsi_id" => "24"],
            ["id" => "232", "nama_kota" => "Kabupaten Lebak", "provinsi_id" => "3"],
            ["id" => "233", "nama_kota" => "Kabupaten Lebong", "provinsi_id" => "4"],
            ["id" => "234", "nama_kota" => "Kabupaten Lembata", "provinsi_id" => "23"],
            ["id" => "235", "nama_kota" => "Kota Lhokseumawe", "provinsi_id" => "21"],
            ["id" => "236", "nama_kota" => "Kabupaten Lima Puluh Koto/Kota", "provinsi_id" => "32"],
            ["id" => "237", "nama_kota" => "Kabupaten Lingga", "provinsi_id" => "17"],
            ["id" => "238", "nama_kota" => "Kabupaten Lombok Barat", "provinsi_id" => "22"],
            ["id" => "239", "nama_kota" => "Kabupaten Lombok Tengah", "provinsi_id" => "22"],
            ["id" => "240", "nama_kota" => "Kabupaten Lombok Timur", "provinsi_id" => "22"],
            ["id" => "241", "nama_kota" => "Kabupaten Lombok Utara", "provinsi_id" => "22"],
            ["id" => "242", "nama_kota" => "Kota Lubuk Linggau", "provinsi_id" => "33"],
            ["id" => "243", "nama_kota" => "Kabupaten Lumajang", "provinsi_id" => "11"],
            ["id" => "244", "nama_kota" => "Kabupaten Luwu", "provinsi_id" => "28"],
            ["id" => "245", "nama_kota" => "Kabupaten Luwu Timur", "provinsi_id" => "28"],
            ["id" => "246", "nama_kota" => "Kabupaten Luwu Utara", "provinsi_id" => "28"],
            ["id" => "247", "nama_kota" => "Kabupaten Madiun", "provinsi_id" => "11"],
            ["id" => "248", "nama_kota" => "Kota Madiun", "provinsi_id" => "11"],
            ["id" => "249", "nama_kota" => "Kabupaten Magelang", "provinsi_id" => "10"],
            ["id" => "250", "nama_kota" => "Kota Magelang", "provinsi_id" => "10"],
            ["id" => "251", "nama_kota" => "Kabupaten Magetan", "provinsi_id" => "11"],
            ["id" => "252", "nama_kota" => "Kabupaten Majalengka", "provinsi_id" => "9"],
            ["id" => "253", "nama_kota" => "Kabupaten Majene", "provinsi_id" => "27"],
            ["id" => "254", "nama_kota" => "Kota Makassar", "provinsi_id" => "28"],
            ["id" => "255", "nama_kota" => "Kabupaten Malang", "provinsi_id" => "11"],
            ["id" => "256", "nama_kota" => "Kota Malang", "provinsi_id" => "11"],
            ["id" => "257", "nama_kota" => "Kabupaten Malinau", "provinsi_id" => "16"],
            ["id" => "258", "nama_kota" => "Kabupaten Maluku Barat Daya", "provinsi_id" => "19"],
            ["id" => "259", "nama_kota" => "Kabupaten Maluku Tengah", "provinsi_id" => "19"],
            ["id" => "260", "nama_kota" => "Kabupaten Maluku Tenggara", "provinsi_id" => "19"],
            ["id" => "261", "nama_kota" => "Kabupaten Maluku Tenggara Barat", "provinsi_id" => "19"],
            ["id" => "262", "nama_kota" => "Kabupaten Mamasa", "provinsi_id" => "27"],
            ["id" => "263", "nama_kota" => "Kabupaten Mamberamo Raya", "provinsi_id" => "24"],
            ["id" => "264", "nama_kota" => "Kabupaten Mamberamo Tengah", "provinsi_id" => "24"],
            ["id" => "265", "nama_kota" => "Kabupaten Mamuju", "provinsi_id" => "27"],
            ["id" => "266", "nama_kota" => "Kabupaten Mamuju Utara", "provinsi_id" => "27"],
            ["id" => "267", "nama_kota" => "Kota Manado", "provinsi_id" => "31"],
            ["id" => "268", "nama_kota" => "Kabupaten Mandailing Natal", "provinsi_id" => "34"],
            ["id" => "269", "nama_kota" => "Kabupaten Manggarai", "provinsi_id" => "23"],
            ["id" => "270", "nama_kota" => "Kabupaten Manggarai Barat", "provinsi_id" => "23"],
            ["id" => "271", "nama_kota" => "Kabupaten Manggarai Timur", "provinsi_id" => "23"],
            ["id" => "272", "nama_kota" => "Kabupaten Manokwari", "provinsi_id" => "25"],
            ["id" => "273", "nama_kota" => "Kabupaten Manokwari Selatan", "provinsi_id" => "25"],
            ["id" => "274", "nama_kota" => "Kabupaten Mappi", "provinsi_id" => "24"],
            ["id" => "275", "nama_kota" => "Kabupaten Maros", "provinsi_id" => "28"],
            ["id" => "276", "nama_kota" => "Kota Mataram", "provinsi_id" => "22"],
            ["id" => "277", "nama_kota" => "Kabupaten Maybrat", "provinsi_id" => "25"],
            ["id" => "278", "nama_kota" => "Kota Medan", "provinsi_id" => "34"],
            ["id" => "279", "nama_kota" => "Kabupaten Melawi", "provinsi_id" => "12"],
            ["id" => "280", "nama_kota" => "Kabupaten Merangin", "provinsi_id" => "8"],
            ["id" => "281", "nama_kota" => "Kabupaten Merauke", "provinsi_id" => "24"],
            ["id" => "282", "nama_kota" => "Kabupaten Mesuji", "provinsi_id" => "18"],
            ["id" => "283", "nama_kota" => "Kota Metro", "provinsi_id" => "18"],
            ["id" => "284", "nama_kota" => "Kabupaten Mimika", "provinsi_id" => "24"],
            ["id" => "285", "nama_kota" => "Kabupaten Minahasa", "provinsi_id" => "31"],
            ["id" => "286", "nama_kota" => "Kabupaten Minahasa Selatan", "provinsi_id" => "31"],
            ["id" => "287", "nama_kota" => "Kabupaten Minahasa Tenggara", "provinsi_id" => "31"],
            ["id" => "288", "nama_kota" => "Kabupaten Minahasa Utara", "provinsi_id" => "31"],
            ["id" => "289", "nama_kota" => "Kabupaten Mojokerto", "provinsi_id" => "11"],
            ["id" => "290", "nama_kota" => "Kota Mojokerto", "provinsi_id" => "11"],
            ["id" => "291", "nama_kota" => "Kabupaten Morowali", "provinsi_id" => "29"],
            ["id" => "292", "nama_kota" => "Kabupaten Muara Enim", "provinsi_id" => "33"],
            ["id" => "293", "nama_kota" => "Kabupaten Muaro Jambi", "provinsi_id" => "8"],
            ["id" => "294", "nama_kota" => "Kabupaten Muko Muko", "provinsi_id" => "4"],
            ["id" => "295", "nama_kota" => "Kabupaten Muna", "provinsi_id" => "30"],
            ["id" => "296", "nama_kota" => "Kabupaten Murung Raya", "provinsi_id" => "14"],
            ["id" => "297", "nama_kota" => "Kabupaten Musi Banyuasin", "provinsi_id" => "33"],
            ["id" => "298", "nama_kota" => "Kabupaten Musi Rawas", "provinsi_id" => "33"],
            ["id" => "299", "nama_kota" => "Kabupaten Nabire", "provinsi_id" => "24"],
            ["id" => "300", "nama_kota" => "Kabupaten Nagan Raya", "provinsi_id" => "21"],
            ["id" => "301", "nama_kota" => "Kabupaten Nagekeo", "provinsi_id" => "23"],
            ["id" => "302", "nama_kota" => "Kabupaten Natuna", "provinsi_id" => "17"],
            ["id" => "303", "nama_kota" => "Kabupaten Nduga", "provinsi_id" => "24"],
            ["id" => "304", "nama_kota" => "Kabupaten Ngada", "provinsi_id" => "23"],
            ["id" => "305", "nama_kota" => "Kabupaten Nganjuk", "provinsi_id" => "11"],
            ["id" => "306", "nama_kota" => "Kabupaten Ngawi", "provinsi_id" => "11"],
            ["id" => "307", "nama_kota" => "Kabupaten Nias", "provinsi_id" => "34"],
            ["id" => "308", "nama_kota" => "Kabupaten Nias Barat", "provinsi_id" => "34"],
            ["id" => "309", "nama_kota" => "Kabupaten Nias Selatan", "provinsi_id" => "34"],
            ["id" => "310", "nama_kota" => "Kabupaten Nias Utara", "provinsi_id" => "34"],
            ["id" => "311", "nama_kota" => "Kabupaten Nunukan", "provinsi_id" => "16"],
            ["id" => "312", "nama_kota" => "Kabupaten Ogan Ilir", "provinsi_id" => "33"],
            ["id" => "313", "nama_kota" => "Kabupaten Ogan Komering Ilir", "provinsi_id" => "33"],
            ["id" => "314", "nama_kota" => "Kabupaten Ogan Komering Ulu", "provinsi_id" => "33"],
            ["id" => "315", "nama_kota" => "Kabupaten Ogan Komering Ulu Selatan", "provinsi_id" => "33"],
            ["id" => "316", "nama_kota" => "Kabupaten Ogan Komering Ulu Timur", "provinsi_id" => "33"],
            ["id" => "317", "nama_kota" => "Kabupaten Pacitan", "provinsi_id" => "11"],
            ["id" => "318", "nama_kota" => "Kota Padang", "provinsi_id" => "32"],
            ["id" => "319", "nama_kota" => "Kabupaten Padang Lawas", "provinsi_id" => "34"],
            ["id" => "320", "nama_kota" => "Kabupaten Padang Lawas Utara", "provinsi_id" => "34"],
            ["id" => "321", "nama_kota" => "Kota Padang Panjang", "provinsi_id" => "32"],
            ["id" => "322", "nama_kota" => "Kabupaten Padang Pariaman", "provinsi_id" => "32"],
            ["id" => "323", "nama_kota" => "Kota Padang Sidempuan", "provinsi_id" => "34"],
            ["id" => "324", "nama_kota" => "Kota Pagar Alam", "provinsi_id" => "33"],
            ["id" => "325", "nama_kota" => "Kabupaten Pakpak Bharat", "provinsi_id" => "34"],
            ["id" => "326", "nama_kota" => "Kota Palangka Raya", "provinsi_id" => "14"],
            ["id" => "327", "nama_kota" => "Kota Palembang", "provinsi_id" => "33"],
            ["id" => "328", "nama_kota" => "Kota Palopo", "provinsi_id" => "28"],
            ["id" => "329", "nama_kota" => "Kota Palu", "provinsi_id" => "29"],
            ["id" => "330", "nama_kota" => "Kabupaten Pamekasan", "provinsi_id" => "11"],
            ["id" => "331", "nama_kota" => "Kabupaten Pandeglang", "provinsi_id" => "3"],
            ["id" => "332", "nama_kota" => "Kabupaten Pangandaran", "provinsi_id" => "9"],
            ["id" => "333", "nama_kota" => "Kabupaten Pangkajene Kepulauan", "provinsi_id" => "28"],
            ["id" => "334", "nama_kota" => "Kota Pangkal Pinang", "provinsi_id" => "2"],
            ["id" => "335", "nama_kota" => "Kabupaten Paniai", "provinsi_id" => "24"],
            ["id" => "336", "nama_kota" => "Kota Parepare", "provinsi_id" => "28"],
            ["id" => "337", "nama_kota" => "Kota Pariaman", "provinsi_id" => "32"],
            ["id" => "338", "nama_kota" => "Kabupaten Parigi Moutong", "provinsi_id" => "29"],
            ["id" => "339", "nama_kota" => "Kabupaten Pasaman", "provinsi_id" => "32"],
            ["id" => "340", "nama_kota" => "Kabupaten Pasaman Barat", "provinsi_id" => "32"],
            ["id" => "341", "nama_kota" => "Kabupaten Paser", "provinsi_id" => "15"],
            ["id" => "342", "nama_kota" => "Kabupaten Pasuruan", "provinsi_id" => "11"],
            ["id" => "343", "nama_kota" => "Kota Pasuruan", "provinsi_id" => "11"],
            ["id" => "344", "nama_kota" => "Kabupaten Pati", "provinsi_id" => "10"],
            ["id" => "345", "nama_kota" => "Kota Payakumbuh", "provinsi_id" => "32"],
            ["id" => "346", "nama_kota" => "Kabupaten Pegunungan Arfak", "provinsi_id" => "25"],
            ["id" => "347", "nama_kota" => "Kabupaten Pegunungan Bintang", "provinsi_id" => "24"],
            ["id" => "348", "nama_kota" => "Kabupaten Pekalongan", "provinsi_id" => "10"],
            ["id" => "349", "nama_kota" => "Kota Pekalongan", "provinsi_id" => "10"],
            ["id" => "350", "nama_kota" => "Kota Pekanbaru", "provinsi_id" => "26"],
            ["id" => "351", "nama_kota" => "Kabupaten Pelalawan", "provinsi_id" => "26"],
            ["id" => "352", "nama_kota" => "Kabupaten Pemalang", "provinsi_id" => "10"],
            ["id" => "353", "nama_kota" => "Kota Pematang Siantar", "provinsi_id" => "34"],
            ["id" => "354", "nama_kota" => "Kabupaten Penajam Paser Utara", "provinsi_id" => "15"],
            ["id" => "355", "nama_kota" => "Kabupaten Pesawaran", "provinsi_id" => "18"],
            ["id" => "356", "nama_kota" => "Kabupaten Pesisir Barat", "provinsi_id" => "18"],
            ["id" => "357", "nama_kota" => "Kabupaten Pesisir Selatan", "provinsi_id" => "32"],
            ["id" => "358", "nama_kota" => "Kabupaten Pidie", "provinsi_id" => "21"],
            ["id" => "359", "nama_kota" => "Kabupaten Pidie Jaya", "provinsi_id" => "21"],
            ["id" => "360", "nama_kota" => "Kabupaten Pinrang", "provinsi_id" => "28"],
            ["id" => "361", "nama_kota" => "Kabupaten Pohuwato", "provinsi_id" => "7"],
            ["id" => "362", "nama_kota" => "Kabupaten Polewali Mandar", "provinsi_id" => "27"],
            ["id" => "363", "nama_kota" => "Kabupaten Ponorogo", "provinsi_id" => "11"],
            ["id" => "364", "nama_kota" => "Kabupaten Pontianak", "provinsi_id" => "12"],
            ["id" => "365", "nama_kota" => "Kota Pontianak", "provinsi_id" => "12"],
            ["id" => "366", "nama_kota" => "Kabupaten Poso", "provinsi_id" => "29"],
            ["id" => "367", "nama_kota" => "Kota Prabumulih", "provinsi_id" => "33"],
            ["id" => "368", "nama_kota" => "Kabupaten Pringsewu", "provinsi_id" => "18"],
            ["id" => "369", "nama_kota" => "Kabupaten Probolinggo", "provinsi_id" => "11"],
            ["id" => "370", "nama_kota" => "Kota Probolinggo", "provinsi_id" => "11"],
            ["id" => "371", "nama_kota" => "Kabupaten Pulang Pisau", "provinsi_id" => "14"],
            ["id" => "372", "nama_kota" => "Kabupaten Pulau Morotai", "provinsi_id" => "20"],
            ["id" => "373", "nama_kota" => "Kabupaten Puncak", "provinsi_id" => "24"],
            ["id" => "374", "nama_kota" => "Kabupaten Puncak Jaya", "provinsi_id" => "24"],
            ["id" => "375", "nama_kota" => "Kabupaten Purbalingga", "provinsi_id" => "10"],
            ["id" => "376", "nama_kota" => "Kabupaten Purwakarta", "provinsi_id" => "9"],
            ["id" => "377", "nama_kota" => "Kabupaten Purworejo", "provinsi_id" => "10"],
            ["id" => "378", "nama_kota" => "Kabupaten Raja Ampat", "provinsi_id" => "25"],
            ["id" => "379", "nama_kota" => "Kabupaten Rejang Lebong", "provinsi_id" => "4"],
            ["id" => "380", "nama_kota" => "Kabupaten Rembang", "provinsi_id" => "10"],
            ["id" => "381", "nama_kota" => "Kabupaten Rokan Hilir", "provinsi_id" => "26"],
            ["id" => "382", "nama_kota" => "Kabupaten Rokan Hulu", "provinsi_id" => "26"],
            ["id" => "383", "nama_kota" => "Kabupaten Rote Ndao", "provinsi_id" => "23"],
            ["id" => "384", "nama_kota" => "Kota Sabang", "provinsi_id" => "21"],
            ["id" => "385", "nama_kota" => "Kabupaten Sabu Raijua", "provinsi_id" => "23"],
            ["id" => "386", "nama_kota" => "Kota Salatiga", "provinsi_id" => "10"],
            ["id" => "387", "nama_kota" => "Kota Samarinda", "provinsi_id" => "15"],
            ["id" => "388", "nama_kota" => "Kabupaten Sambas", "provinsi_id" => "12"],
            ["id" => "389", "nama_kota" => "Kabupaten Samosir", "provinsi_id" => "34"],
            ["id" => "390", "nama_kota" => "Kabupaten Sampang", "provinsi_id" => "11"],
            ["id" => "391", "nama_kota" => "Kabupaten Sanggau", "provinsi_id" => "12"],
            ["id" => "392", "nama_kota" => "Kabupaten Sarmi", "provinsi_id" => "24"],
            ["id" => "393", "nama_kota" => "Kabupaten Sarolangun", "provinsi_id" => "8"],
            ["id" => "394", "nama_kota" => "Kota Sawah Lunto", "provinsi_id" => "32"],
            ["id" => "395", "nama_kota" => "Kabupaten Sekadau", "provinsi_id" => "12"],
            ["id" => "396", "nama_kota" => "Kabupaten Selayar (Kepulauan Selayar)", "provinsi_id" => "28"],
            ["id" => "397", "nama_kota" => "Kabupaten Seluma", "provinsi_id" => "4"],
            ["id" => "398", "nama_kota" => "Kabupaten Semarang", "provinsi_id" => "10"],
            ["id" => "399", "nama_kota" => "Kota Semarang", "provinsi_id" => "10"],
            ["id" => "400", "nama_kota" => "Kabupaten Seram Bagian Barat", "provinsi_id" => "19"],
            ["id" => "401", "nama_kota" => "Kabupaten Seram Bagian Timur", "provinsi_id" => "19"],
            ["id" => "402", "nama_kota" => "Kabupaten Serang", "provinsi_id" => "3"],
            ["id" => "403", "nama_kota" => "Kota Serang", "provinsi_id" => "3"],
            ["id" => "404", "nama_kota" => "Kabupaten Serdang Bedagai", "provinsi_id" => "34"],
            ["id" => "405", "nama_kota" => "Kabupaten Seruyan", "provinsi_id" => "14"],
            ["id" => "406", "nama_kota" => "Kabupaten Siak", "provinsi_id" => "26"],
            ["id" => "407", "nama_kota" => "Kota Sibolga", "provinsi_id" => "34"],
            ["id" => "408", "nama_kota" => "Kabupaten Sidenreng Rappang/Rapang", "provinsi_id" => "28"],
            ["id" => "409", "nama_kota" => "Kabupaten Sidoarjo", "provinsi_id" => "11"],
            ["id" => "410", "nama_kota" => "Kabupaten Sigi", "provinsi_id" => "29"],
            ["id" => "411", "nama_kota" => "Kabupaten Sijunjung (Sawah Lunto Sijunjung)", "provinsi_id" => "32"],
            ["id" => "412", "nama_kota" => "Kabupaten Sikka", "provinsi_id" => "23"],
            ["id" => "413", "nama_kota" => "Kabupaten Simalungun", "provinsi_id" => "34"],
            ["id" => "414", "nama_kota" => "Kabupaten Simeulue", "provinsi_id" => "21"],
            ["id" => "415", "nama_kota" => "Kota Singkawang", "provinsi_id" => "12"],
            ["id" => "416", "nama_kota" => "Kabupaten Sinjai", "provinsi_id" => "28"],
            ["id" => "417", "nama_kota" => "Kabupaten Sintang", "provinsi_id" => "12"],
            ["id" => "418", "nama_kota" => "Kabupaten Situbondo", "provinsi_id" => "11"],
            ["id" => "419", "nama_kota" => "Kabupaten Sleman", "provinsi_id" => "5"],
            ["id" => "420", "nama_kota" => "Kabupaten Solok", "provinsi_id" => "32"],
            ["id" => "421", "nama_kota" => "Kota Solok", "provinsi_id" => "32"],
            ["id" => "422", "nama_kota" => "Kabupaten Solok Selatan", "provinsi_id" => "32"],
            ["id" => "423", "nama_kota" => "Kabupaten Soppeng", "provinsi_id" => "28"],
            ["id" => "424", "nama_kota" => "Kabupaten Sorong", "provinsi_id" => "25"],
            ["id" => "425", "nama_kota" => "Kota Sorong", "provinsi_id" => "25"],
            ["id" => "426", "nama_kota" => "Kabupaten Sorong Selatan", "provinsi_id" => "25"],
            ["id" => "427", "nama_kota" => "Kabupaten Sragen", "provinsi_id" => "10"],
            ["id" => "428", "nama_kota" => "Kabupaten Subang", "provinsi_id" => "9"],
            ["id" => "429", "nama_kota" => "Kota Subulussalam", "provinsi_id" => "21"],
            ["id" => "430", "nama_kota" => "Kabupaten Sukabumi", "provinsi_id" => "9"],
            ["id" => "431", "nama_kota" => "Kota Sukabumi", "provinsi_id" => "9"],
            ["id" => "432", "nama_kota" => "Kabupaten Sukamara", "provinsi_id" => "14"],
            ["id" => "433", "nama_kota" => "Kabupaten Sukoharjo", "provinsi_id" => "10"],
            ["id" => "434", "nama_kota" => "Kabupaten Sumba Barat", "provinsi_id" => "23"],
            ["id" => "435", "nama_kota" => "Kabupaten Sumba Barat Daya", "provinsi_id" => "23"],
            ["id" => "436", "nama_kota" => "Kabupaten Sumba Tengah", "provinsi_id" => "23"],
            ["id" => "437", "nama_kota" => "Kabupaten Sumba Timur", "provinsi_id" => "23"],
            ["id" => "438", "nama_kota" => "Kabupaten Sumbawa", "provinsi_id" => "22"],
            ["id" => "439", "nama_kota" => "Kabupaten Sumbawa Barat", "provinsi_id" => "22"],
            ["id" => "440", "nama_kota" => "Kabupaten Sumedang", "provinsi_id" => "9"],
            ["id" => "441", "nama_kota" => "Kabupaten Sumenep", "provinsi_id" => "11"],
            ["id" => "442", "nama_kota" => "Kota Sungaipenuh", "provinsi_id" => "8"],
            ["id" => "443", "nama_kota" => "Kabupaten Supiori", "provinsi_id" => "24"],
            ["id" => "444", "nama_kota" => "Kota Surabaya", "provinsi_id" => "11"],
            ["id" => "445", "nama_kota" => "Kota Surakarta (Solo)", "provinsi_id" => "10"],
            ["id" => "446", "nama_kota" => "Kabupaten Tabalong", "provinsi_id" => "13"],
            ["id" => "447", "nama_kota" => "Kabupaten Tabanan", "provinsi_id" => "1"],
            ["id" => "448", "nama_kota" => "Kabupaten Takalar", "provinsi_id" => "28"],
            ["id" => "449", "nama_kota" => "Kabupaten Tambrauw", "provinsi_id" => "25"],
            ["id" => "450", "nama_kota" => "Kabupaten Tana Tidung", "provinsi_id" => "16"],
            ["id" => "451", "nama_kota" => "Kabupaten Tana Toraja", "provinsi_id" => "28"],
            ["id" => "452", "nama_kota" => "Kabupaten Tanah Bumbu", "provinsi_id" => "13"],
            ["id" => "453", "nama_kota" => "Kabupaten Tanah Datar", "provinsi_id" => "32"],
            ["id" => "454", "nama_kota" => "Kabupaten Tanah Laut", "provinsi_id" => "13"],
            ["id" => "455", "nama_kota" => "Kabupaten Tangerang", "provinsi_id" => "3"],
            ["id" => "456", "nama_kota" => "Kota Tangerang", "provinsi_id" => "3"],
            ["id" => "457", "nama_kota" => "Kota Tangerang Selatan", "provinsi_id" => "3"],
            ["id" => "458", "nama_kota" => "Kabupaten Tanggamus", "provinsi_id" => "18"],
            ["id" => "459", "nama_kota" => "Kota Tanjung Balai", "provinsi_id" => "34"],
            ["id" => "460", "nama_kota" => "Kabupaten Tanjung Jabung Barat", "provinsi_id" => "8"],
            ["id" => "461", "nama_kota" => "Kabupaten Tanjung Jabung Timur", "provinsi_id" => "8"],
            ["id" => "462", "nama_kota" => "Kota Tanjung Pinang", "provinsi_id" => "17"],
            ["id" => "463", "nama_kota" => "Kabupaten Tapanuli Selatan", "provinsi_id" => "34"],
            ["id" => "464", "nama_kota" => "Kabupaten Tapanuli Tengah", "provinsi_id" => "34"],
            ["id" => "465", "nama_kota" => "Kabupaten Tapanuli Utara", "provinsi_id" => "34"],
            ["id" => "466", "nama_kota" => "Kabupaten Tapin", "provinsi_id" => "13"],
            ["id" => "467", "nama_kota" => "Kota Tarakan", "provinsi_id" => "16"],
            ["id" => "468", "nama_kota" => "Kabupaten Tasikmalaya", "provinsi_id" => "9"],
            ["id" => "469", "nama_kota" => "Kota Tasikmalaya", "provinsi_id" => "9"],
            ["id" => "470", "nama_kota" => "Kota Tebing Tinggi", "provinsi_id" => "34"],
            ["id" => "471", "nama_kota" => "Kabupaten Tebo", "provinsi_id" => "8"],
            ["id" => "472", "nama_kota" => "Kabupaten Tegal", "provinsi_id" => "10"],
            ["id" => "473", "nama_kota" => "Kota Tegal", "provinsi_id" => "10"],
            ["id" => "474", "nama_kota" => "Kabupaten Teluk Bintuni", "provinsi_id" => "25"],
            ["id" => "475", "nama_kota" => "Kabupaten Teluk Wondama", "provinsi_id" => "25"],
            ["id" => "476", "nama_kota" => "Kabupaten Temanggung", "provinsi_id" => "10"],
            ["id" => "477", "nama_kota" => "Kota Ternate", "provinsi_id" => "20"],
            ["id" => "478", "nama_kota" => "Kota Tidore Kepulauan", "provinsi_id" => "20"],
            ["id" => "479", "nama_kota" => "Kabupaten Timor Tengah Selatan", "provinsi_id" => "23"],
            ["id" => "480", "nama_kota" => "Kabupaten Timor Tengah Utara", "provinsi_id" => "23"],
            ["id" => "481", "nama_kota" => "Kabupaten Toba Samosir", "provinsi_id" => "34"],
            ["id" => "482", "nama_kota" => "Kabupaten Tojo Una-Una", "provinsi_id" => "29"],
            ["id" => "483", "nama_kota" => "Kabupaten Toli-Toli", "provinsi_id" => "29"],
            ["id" => "484", "nama_kota" => "Kabupaten Tolikara", "provinsi_id" => "24"],
            ["id" => "485", "nama_kota" => "Kota Tomohon", "provinsi_id" => "31"],
            ["id" => "486", "nama_kota" => "Kabupaten Toraja Utara", "provinsi_id" => "28"],
            ["id" => "487", "nama_kota" => "Kabupaten Trenggalek", "provinsi_id" => "11"],
            ["id" => "488", "nama_kota" => "Kota Tual", "provinsi_id" => "19"],
            ["id" => "489", "nama_kota" => "Kabupaten Tuban", "provinsi_id" => "11"],
            ["id" => "490", "nama_kota" => "Kabupaten Tulang Bawang", "provinsi_id" => "18"],
            ["id" => "491", "nama_kota" => "Kabupaten Tulang Bawang Barat", "provinsi_id" => "18"],
            ["id" => "492", "nama_kota" => "Kabupaten Tulungagung", "provinsi_id" => "11"],
            ["id" => "493", "nama_kota" => "Kabupaten Wajo", "provinsi_id" => "28"],
            ["id" => "494", "nama_kota" => "Kabupaten Wakatobi", "provinsi_id" => "30"],
            ["id" => "495", "nama_kota" => "Kabupaten Waropen", "provinsi_id" => "24"],
            ["id" => "496", "nama_kota" => "Kabupaten Way Kanan", "provinsi_id" => "18"],
            ["id" => "497", "nama_kota" => "Kabupaten Wonogiri", "provinsi_id" => "10"],
            ["id" => "498", "nama_kota" => "Kabupaten Wonosobo", "provinsi_id" => "10"],
            ["id" => "499", "nama_kota" => "Kabupaten Yahukimo", "provinsi_id" => "24"],
            ["id" => "500", "nama_kota" => "Kabupaten Yalimo", "provinsi_id" => "24"],
            ["id" => "501", "nama_kota" => "Kota Yogyakarta", "provinsi_id" => "5"],
        ];

        foreach ($datas as $data) {
            Kota::create($data);
        }
    }
}
